"""Add notable_quotes to Summary model

Revision ID: dbc1ea0d7a3c
Revises: 33c785a05efe
Create Date: 2025-03-02 17:14:45.817007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc1ea0d7a3c'
down_revision = '33c785a05efe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('notable_quotes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'notable_quotes')
    # ### end Alembic commands ### 